[package]
name = "dogshaiters"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13", features = ["webgl2"] }
bevy_web_asset = "0.8.0"
rand = "0.8.5"
wasm-bindgen = "0.2.83"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 's'
